import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar.js";
import Main from "../components/Main.js";
import Sectors from "../components/Sectors";
import Gallery from "../components/Gallery";
import Team from "../components/Team";
import Footer from "../components/Footer";
import dynamic from "next/dynamic";

export default function Home() {
  return (
    <div className="font-roman">
      <Head>
        <title>Ivre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logoicon.ico" />
      </Head>

      <Navbar />
      <Main />
      <Sectors />
      <Gallery />
      <Team />
      <Footer />
    </div>
  );
}
